name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Build Docker Image
        run: docker build -t fastapi-app .
      
      - name: Run Docker Container
        run: docker run -d -p 80:80 fastapi-app

      - name: Retrieve Container IP
        id: container_ip
        run: echo ::set-output name=ip::$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q))

      - name: Update README with API URL
        run: |
          echo "API URL: http://${{ steps.container_ip.outputs.ip }}:80" > README.md
